---
language: ruby
rvm:
  - 2.5.1
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
jobs:
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/rails_4.gemfile
env:
  - GENEALOGY_TEST_DB=mysql
  - GENEALOGY_TEST_DB=postgres
services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database genealogy_test;'
  - psql -c 'create database genealogy_test;' -U postgres
