sqlite:
  adapter: sqlite3
  database: spec/test.sqlite3.db

## developer local
# mysql:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: genealogy_test
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock

## travis specific
mysql:
  adapter: mysql2
  encoding: utf8
  database: genealogy_test
  username: travis

postgres:
  adapter: postgresql
  database: genealogy_test
  username: postgres
